export enum NotificationType {
  DISPUTE_CREATED = "DISPUTE_CREATED",
  DISPUTE_ASSIGNED = "DISPUTE_ASSIGNED",
  DISPUTE_ESCALATED = "DISPUTE_ESCALATED",
  DISPUTE_RESOLVED = "DISPUTE_RESOLVED",
  DISPUTE_CLOSED = "DISPUTE_CLOSED",
  SLA_WARNING = "SLA_WARNING",
  SLA_BREACH = "SLA_BREACH",
}
