export interface AuditChangeLog {
  [key: string]: any
}

export interface AuditAction {
  DISPUTE_CREATED: "DISPUTE_CREATED"
  DISPUTE_TRANSITIONED: "DISPUTE_TRANSITIONED"
  DISPUTE_ASSIGNED: "DISPUTE_ASSIGNED"
  DISPUTE_SYSTEM_ESCALATION: "DISPUTE_SYSTEM_ESCALATION"
  SLA_CREATED: "SLA_CREATED"
  SLA_UPDATED: "SLA_UPDATED"
}
